#!/usr/bin/env python3
"""Campaign links are generated by build.py; validate them before publishing."""
import subprocess,sys
from pathlib import Path
root=Path(__file__).resolve().parent
sys.exit(subprocess.call([sys.executable,str(root/'validate.py')]))
